# Generated by Django 5.2.9 on 2025-12-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='accounts.escritorio')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('titulo', models.CharField(help_text='Ex: Ação Trabalhista vs Empresa X', max_length=255, verbose_name='Título/Ação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado'), ('FINALIZADO', 'Finalizado')], default='ATIVO', max_length=20)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='core.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='accounts.escritorio')),
            ],
        ),
    ]
