# Generated by Django 5.2.9 on 2025-12-11 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processo',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título/Ação'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.escritorio')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('AUDIENCIA', 'Audiência'), ('PRAZO', 'Prazo Fatal'), ('REUNIAO', 'Reunião'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.escritorio')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.processo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('titular', models.BooleanField(default=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.escritorio')),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.juiz'),
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.escritorio')),
            ],
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('comarca', models.CharField(max_length=200)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.escritorio')),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vara'),
        ),
    ]
